### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by KevinSteinhauser** [HardCorePawn/multibit_recovery#10]
Hello, 
This is what I get when I run find_unspent_multibitHD_txes.py
I know I have the correct password. Any idea what the issue is?

Traceback (most recent call last):
  File "find_unspent_multibitHD_txes.py", line 281, in <module>
    wallet = load_wallet(wallet_file, get_password)
  File "find_unspent_multibitHD_txes.py", line 131, in load_wallet
    password = get_password_fn(takes_long)
  File "find_unspent_multibitHD_txes.py", line 269, in get_password
    password = password.decode(encoding)  # convert from terminal's encoding to unicode
AttributeError: 'str' object has no attribute 'decode'

**Comment by HardCorePawn** [comment]
What version of Python are you using? try running `python -V` from the commandline... to check the version.

These scripts only work with Python 2
