### ISSUE TITLE
ImportError: No module named google.protobuf

### ISSUE THREAD

**Issue by Tongie969** [HardCorePawn/multibit_recovery#11]
Hello HardCorePawn! 

Thanks for offering your hard work here! I tried to use "decrypt_multibit_classic_walletkeys.py" but I am facing this import error. 

+Traceback (most recent call last):
  File "decrypt_multibit_classic_walletkeys.py", line 47, in <module>
    import wallet_pb2, binascii, bitcoin
  File "/home/tongie/multibit_recovery/wallet_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

I also could imagine some misconfiguration by me. OS is Ubuntu 20.04 and Python 2.7.18. 

I will try it on Windows tomorrow and let you know.

**Comment by HardCorePawn** [comment]
Did you install the google protobuf module in Python? As per the Linux installation instructions: https://github.com/HardCorePawn/multibit_recovery#linux

specifically:
>To install dependencies: `pip install protobuf pylibscrypt bitcoin`

**Comment by Tongie969** [comment]
Thanks for your fast response! 

I already had the dependencies installed. 

$ pip install protobuf pylibscrypt bitcoin
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (3.6.1)
Requirement already satisfied: pylibscrypt in ./.local/lib/python3.8/site-packages (2.0.0)
Requirement already satisfied: bitcoin in ./.local/lib/python3.8/site-packages (1.1.42)

Maybe I try to start with the wrong input. 

sudo python2 decrypt_multibit_classic_walletkeys.py multibit-XXX.wallet

and I have just placed that one small .wallet file in the folder. I hope that right. 

Sorry for noobing around a little bit ;)

**Comment by HardCorePawn** [comment]
It's ok... the whole Python 2 v. Python 3 thing can be a bit problematic... if you look at your output above, you'll see that you have installed the dependencies in Python **3**... but you're trying to run with Python 2...

Try: `sudo python2 -m pip install protobuf pylibscrypt bitcoin`

that should run the Python 2 version of pip and install the dependencies in the right place.

**Comment by Tongie969** [comment]
Captain, your scrip is working great, I can't wait to ask for your address. 

My mate was sure there is no password on it, but there is... 

Let's hope john fixes it, and I will appreciate your help.

**Comment by HardCorePawn** [comment]
Glad you managed to get it sorted and up and running. Let me know if you need any more help.
