### ISSUE TITLE
cipher multibit HD file

### ISSUE THREAD

**Issue by CryptoRecoveryWorldwideCZ** [HardCorePawn/multibit_recovery#12]
Hi, I trying recovery Multibit HD wallet. Wallet is encrypted with password, but i have complete folder. :)) contains mbhd file, then key-backup folder ,rolling-backup folder, wallet-backup folder and wallet-unenc-backup folder. All of this have files. But your code work only for Multibit, not for Multibit HD. As I research, only one chance is with .cipher file, but this tip is for multibit classic. Do You try to compile code for Multibit HD for extract keys? Thank You for reply. Jiri

**Comment by HardCorePawn** [comment]
There is a script for MultiBit HD wallets: https://github.com/HardCorePawn/multibit_recovery#find_unspent_multibithd_txespy

You need the wallet password though. If you don't have the wallet password, none of my scripts will work. You'd need to try bruteforcing the password using: https://github.com/3rdIteration/btcrecover
