### ISSUE TITLE
Files are encrypted

### ISSUE THREAD

**Issue by marbletissue** [HardCorePawn/multibit_recovery#13]
Hey,
I have a wallet from 2013 with all associated files (.key, .wallet, .wallet.cipher)

My problem is that the key is encrypted. 

Are any of your scripts useful if the encryption password is unknown?

Thanks!

**Comment by HardCorePawn** [comment]
Unfortunately, all the scripts require the password to function properly. They aren't useful for "cracking" passwords, per se, as they need the password to decrypt the files and output the private keys etc.

You might have better luck using something like hashcat for the password recovery (assuming the password wasn't too complex and/or you have a decent amount of GPU power etc). https://hashcat.net/hashcat/
